In [49]:
import numpy as np

dash = ' --- '*3
line1 = '| 0 | | 0 | | 0 |'   
line2 = '| 0 | | 0 | | 0 |'   
line3 = '| 0 | | 0 | | 0 |'   
        
# Sample
sample = np.ones((3,3))
m = 0

framework = [dash,line1,dash,dash,line2,dash,dash,line3,dash]

def matt():
    global m   
    for i in range(sample.shape[0]):
#         mat[i] = int(input('Enter your number: '))
        for j in range(sample.shape[1]):
            m += 1
            sample[i][j] = m
    print('This is a sample')
    print(sample)
    
matt()

print('Player 1 uses X')
print('Player 2 uses O')

position_used  = []
def position():
    global question
    question = int(input('Using the sample,pick a number you"d like to replace with your value: '))
    position_used.append(question)
    return question


def player1():
    player1 = input('Enter your value:')
    
def player2():
    player1 = input('Enter your value:')    
    
# players = [player1(),player2()]  

list1 = []

def index_locater():
    n = 1                 
    for j in range(3):
        global list1
        index_location = line1.index('0',n)
        n += 4
        list1.append(index_location)
index_locater()
print(list1)

def tic_tac_toe():
    # For the tic tac toe game layout

        
    for i in range(3):
            global framework
            position()


            if position_used[i] == 1:
                framework[2]  = framework[2].replace(framework[2][2],'X')
            if  position_used[i] == 2:
                framework[2]  = framework[2].replace(framework[2][8],'X')
            if position_used[i]== 3:
                framework[2]  = framework[2].replace(framework[2][14],'X')

            if position_used[i] == 4:
                framework[4]  = framework[4].replace(framework[2][2],'X')
            if position_used[i] == 5:
                framework[4]  = framework[4].replace(framework[2][8],'X')
            if  position_used[i]== 6:
                framework[4]  = framework[4].replace(framework[2][14],'X')
                
            if position_used[i] == 7:
                framework[7]  = framework[7].replace(framework[2][2],'X')
            if position_used[i] == 8:
                framework[7]  = framework[7].replace(framework[2][8],'X')
            if position_used[i] == 9:
                framework[7]  = framework[7].replace(framework[2][14],'X')

    for j in range(len(framework)):
        print(framework[j])
            
        # else:
            # print(dash)
            
                
     # The fixation of values
#     if question == True:
#         if player1 == True:
#             if question == 1:
#                 line.replace(line[2],'X')
#             if question == 2:
#                 line.replace(line[7],'X')
#             if question == 3:
#                 line.replace(line[12],'X')

tic_tac_toe()   
# Zero means empty slots    

This is a sample
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Player 1 uses X
Player 2 uses O
[2, 8, 14]
 ---  ---  --- 
| 0 | | 0 | | 0 |
X---XX---XX---X
 ---  ---  --- 
| 0 | | 0 | | 0 |
 ---  ---  --- 
 ---  ---  --- 
| 0 | | 0 | | 0 |
 ---  ---  --- 


In [45]:
position_used
line2
line2.replace(line2[2],'X')
line2[12]

# list2 = "456"
# list2.replace(list2[2],"8")

'|'