In [1]:
import numpy as np

dash = ' --- '*3
line = '| 0 |'*3   
        
# Sample
sample = np.ones((3,3))
m = 0

def matt():
    global m   
    for i in range(sample.shape[0]):
#         mat[i] = int(input('Enter your number: '))
        for j in range(sample.shape[1]):
            m += 1
            sample[i][j] = m
    print('This is a sample')
    print(sample)
    
matt()

print('Player 1 uses X')
print('Player 2 uses O')

position_used  = []
def position():
    global question
    question = int(input('Using the sample,pick a number you"d like to replace with your value: '))
    position_used.append(question)
    return question


def player1():
    player1 = input('Enter your value:')
    
def player2():
    player1 = input('Enter your value:')    
    
# players = [player1(),player2()]  

list1 = []
n = 1                 

def index_locater():
    for j in range(3):
        global list1
        index_location = line.index('0',n)
        n += 4
        list1.append(index_location)

def tic_tac_toe():
    position()
    # For the tic tac toe game layout
    for i in range(4):
        
        if i == 0:
            print(dash)
            print(line) 
            if position_used[i] == 1:
                line.replace(line[2],'X')
            if  position_used[i] == 2:
                line.replace(line[7],'X')
            if position_used[i]== 3:
                line.replace(line[12],'X')
            

        if i == 1:
            print(dash)
            print(line)
            if position_used[i] == 4:
                line.replace(line[2],'X')
            if position_used[i] == 5:
                line.replace(line[7],'X')
            if  position_used[i]== 6:
                line.replace(line[12],'X')
                
        if i == 2:
            print(dash)
            print(line)
            if position_used[i] == 7:
                line.replace(line[2],'X')
            if position_used[i] == 8:
                line.replace(line[7],'X')
            if position_used[i] == 9:
                line.replace(line[12],'X')
            
        else:
            print(dash)
            
                
     # The fixation of values
#     if question == True:
#         if player1 == True:
#             if question == 1:
#                 line.replace(line[2],'X')
#             if question == 2:
#                 line.replace(line[7],'X')
#             if question == 3:
#                 line.replace(line[12],'X')
                
                             
tic_tac_toe()   
# Zero means empty slots    

This is a sample
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Player 1 uses X
Player 2 uses O
 ---  ---  --- 
| 0 || 0 || 0 |
 ---  ---  --- 
 ---  ---  --- 
| 0 || 0 || 0 |


IndexError: list index out of range