In [25]:
# import numpy as np

# dash = ' --- ' * 3
# line1 = ["|", '0' , '|' , '|',  '0', '|', '|', '0', '|']   
# line2 = ["|", '0' , '|' , '|',  '0', '|', '|', '0', '|']   
# line3 = ["|", '0' , '|' , '|',  '0', '|', '|', '0', '|']   
        
# # Sample
# sample = np.ones((3,3))
# m = 0

# framework = [dash,line1,dash,dash,line2,dash,dash,line3,dash]

# def matt():
#     global m   
#     for i in range(sample.shape[0]):
# #         mat[i] = int(input('Enter your number: '))
#         for j in range(sample.shape[1]):
#             m += 1
#             sample[i][j] = m
#     print('This is a sample')
#     print(sample)
    
# matt()

# print('Player 1 uses X')
# print('Player 2 uses O')

# position_used  = []
# def position():
#     global question
#     question = int(input('Using the sample,pick a number you"d like to replace with your value: '))
#     position_used.append(question)
#     return question


# def player1():
#     player1 = input('Enter your value:')
    
# def player2():
#     player1 = input('Enter your value:')    
    
# # players = [player1(),player2()]  

# # list1 = []

# # def index_locater():
# #     n = 1                 
# #     for j in range(3):
# #         global list1
# #         index_location = line1.index('0',n)
# #         n += 4
# #         list1.append(index_location)
# # index_locater()
# # print(list1)

# def tic_tac_toe():
#     # For the tic tac toe game layout

        
#     for i in range(3):
#             global framework
#             position()


#             if position_used[i] == 1:
#                 line1[1] ='X'
#                 # joint = ('').join(line1)
#             if  position_used[i] == 2:
#                 line1[4] ='X'
#             if position_used[i]== 3:
#                 line1[7] ='X'

#             if position_used[i] == 4:
#                 line2[1] = 'X'
#             if position_used[i] == 5:
#                 line2[4] = 'X'
#             if  position_used[i] == 6:
#                 line2[7] ='X'
                
#             if position_used[i] == 7:
#                 line3[1] = 'X'
#             if position_used[i] == 8:
#                 line3[4] = 'X'
#             if position_used[i] == 9:
#                 line3[7] = 'X'

#     # for j in range(len(framework)):

#     #     print(framework[j])

#     def layout():
#         joint1 = ('').join(line1)
#         joint2 = ('').join(line2)
#         joint3 = ('').join(line3)
        
#         print(dash)
#         print(line1)
#         print(dash)
#         print(dash)
#         print(line2)
#         print(dash)
#         print(dash)
#         print(line3)
#         print(dash)
#     layout()
        

            
#         # else:
#             # print(dash)
            
                
#      # The fixation of values
# #     if question == True:
# #         if player1 == True:
# #             if question == 1:
# #                 line.replace(line[2],'X')
# #             if question == 2:-
# #                 line.replace(line[7],'X')
# #             if question == 3:
# #                 line.replace(line[12],'X')

# tic_tac_toe()   
# Zero means empty slots    

This is a sample
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Player 1 uses X
Player 2 uses O
 ---  ---  --- 
['|', '0', '|', '|', 'X', '|', '|', '0', '|']
 ---  ---  --- 
 ---  ---  --- 
['|', '0', '|', '|', '0', '|', '|', 'X', '|']
 ---  ---  --- 
 ---  ---  --- 
['|', '0', '|', '|', '0', '|', '|', 'X', '|']
 ---  ---  --- 


In [17]:
# # position_used
# # line2
# # line2.replace(line2[6],'X')
# # line = [line2]

# # line.remove(line[0])
# # line = framework
# line1 = ["|", '0' , '|' , '|',  '0', '|', '|', '0', '|']
# line1[1] = 9
# line1
# # line1.index('0')

# # for j in range(len(framework)):
# #     print(line[j])

# # print(line[1][2])
# # line[1].re
# # line
# # list2.replace(list2[2],"8")


# # crate alist of line1
# # access teh things individually


['|', 9, '|', '|', '0', '|', '|', '0', '|']

In [4]:
import numpy as np

sample = np.ones((3,3))
m = 0


def matt():
    global m  
    global sample 
    for i in range(sample.shape[0]):
#         mat[i] = int(input('Enter your number: '))
        for j in range(sample.shape[1]):
            m += 1
            sample[i][j] = m
    print('This is a sample')
    print(sample)
    
matt()


This is a sample
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


X   O   _   

X   _   _   

O   O   X   

